[workspace]
resolver = "2"
members = ["core"]
exclude = ["examples"]

[workspace.package]
authors = ["Nico Burniske"]
edition = "2021"
license = "MIT"
repository = "https://github.com/gaucho-labs/lepton"
version = "0.1.0"